package com.ufsc.webchat.protocol.enums;

public enum PayloadType {
	HOST,
	CONNECTION,
	ROUTING,
	USER_CREATION,
	USER_LISTING,
	DISCONNECTION,
	GROUP_CHAT_CREATION,
	CHAT_LISTING,
	GROUP_CHAT_ADDITION,
	MESSAGE,
	MESSAGE_FORWARDING,
	MESSAGE_LISTING,
	GET_USER_CHAT_ID,
}
