package com.ufsc.webchat.protocol.enums;

public enum PayloadType {
	CONNECTION,
	ROUTING,
	USER_CREATION,
	USER_LISTING,
	USER_APPLICATION_SERVER,
	DISCONNECTION,
	GROUP_CHAT_CREATION,
	CHAT_LISTING,
	GROUP_CHAT_ADDITION,
	MESSAGE,
	MESSAGE_LISTING,
}
