'''
Tipo de payload.
'''

from enum import Enum

class PayloadType(Enum):
    '''
    Tipo de payload.
    '''

    CONNECTION = 'CONNECTION'
    ROUTING = 'ROUTING'
    USER_CREATION = 'USER_CREATION'
    USER_LISTING = 'USER_LISTING'
    USER_APPLICATION_SERVER = 'USER_APPLICATION_SERVER'
    DISCONNECTION = 'DISCONNECTION'
    CHAT_CREATION = 'CHAT_CREATION'
    CHAT_LISTING = 'CHAT_LISTING'
    CHAT_ADDITION = 'CHAT_ADDITION'
    MESSAGE = 'MESSAGE'
    MESSAGE_LISTING = 'MESSAGE_LISTING'
